### PR TITLE
fix: experience bug

### LINKED ISSUE #11: Experience - archive bug fix

### PR DESCRIPTION
**Pull request by mussida**

### CODE REVIEW

File: src/app/components/motion-detection/motion-detection.component.ts [hunk 1]
```diff
@@ -204,6 +204,85 @@ export class MotionDetectionComponent implements AfterViewInit, OnDestroy {
     });
   }
 
+  // spawnImage(row: number, col: number, gridWidth: number, gridHeight: number) {
```
Comment (micheledinelli) [inline src/app/components/motion-detection/motion-detection.component.ts:207]: I would remove this old commented method

File: src/app/components/motion-detection/motion-detection.component.ts [hunk 2]
```diff
@@ -255,16 +335,16 @@ export class MotionDetectionComponent implements AfterViewInit, OnDestroy {
         const scaledWidth = imgWidth * scaleFactor;
         const scaledHeight = imgHeight * scaleFactor;
 
-        const left = (window.innerWidth - scaledWidth) / 2;
-        const top = (window.innerHeight - scaledHeight) / 2;
+        const newLeft = (window.innerWidth - scaledWidth) / 2;
+        const newTop = (window.innerHeight - scaledHeight) / 2;
```
Comment (micheledinelli) [inline src/app/components/motion-detection/motion-detection.component.ts:339]:
```suggestion
        const left = (window.innerWidth - scaledWidth) / 2;
        const top = (window.innerHeight - scaledHeight) / 2;
```

File: src/app/components/motion-detection/motion-detection.component.ts [hunk 3]
```diff
@@ -255,16 +335,16 @@ export class MotionDetectionComponent implements AfterViewInit, OnDestroy {
...
 
         img.style.width = `${scaledWidth}px`;
         img.style.height = `${scaledHeight}px`;
-        img.style.left = `${left}px`;
-        img.style.top = `${top}px`;
-      });
+        img.style.left = `${newLeft}px`;
+        img.style.top = `${newTop}px`;
+      };
```
Comment (micheledinelli) [inline src/app/components/motion-detection/motion-detection.component.ts:345]:
```suggestion
        img.style.left = `${left}px`;
        img.style.top = `${top}px`;
      };
```
